
services:

  consumerA:
    image: ${DOCKER_REGISTRY-}consumer
    build:
        context: .
        dockerfile: Consumer/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - kafka
    depends_on:
      - kafka

  consumerB:
    image: ${DOCKER_REGISTRY-}consumer
    build:
        context: .
        dockerfile: Consumer/Dockerfile
    ports:
      - "8085:8085"
    networks:
      - kafka
    depends_on:
      - kafka

  provider:
    image: ${DOCKER_REGISTRY-}user
    build:
        context: .
        dockerfile: User-producer/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - kafka
    depends_on:
      - kafka

  logconsumer:
    image: ${DOCKER_REGISTRY-}logconsumer
    build:
      context: .
      dockerfile: LogConsumer/Dockerfile
    ports:
       - "8084:8084"
    networks:
       - kafka
    depends_on:
       - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - kafka
            
  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    post_start:
      - command: ["/bin/sh", "-c", "kafka-topics --create --topic user-topic --bootstrap-server kafka:9092 --partitions 3"]
    networks:
      - kafka

  opensearch:
    image: opensearchproject/opensearch
    environment:
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: admin
      network.host: 0.0.0.0
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: true
      compatibility.override_main_response_version: true
    ports:
      - 9200:9200
      - 9600:9600

  
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    depends_on:
      - opensearch


networks:
  kafka:

